version: '3.8'

services:
  # Component Tests
  component-tests:
    image: playwright-tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./playwright-report/component:/app/playwright-report/component
    command: npm run run-ct-test

  # End-to-End Tests
  e2e-tests:
    image: playwright-tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./playwright-report/e2e:/app/playwright-report/e2e
    command: npm run run-e2e-test
