services:
  # Component Tests
  component-tests:
    image: playwright-tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./playwright-report/component:/app/playwright-report/component
      # Mount the component test snapshots directory
      - ./tests/__snapshots__:/app/tests/__snapshots__
    command: npm run run-ct-test

  # End-to-End Tests
  e2e-tests:
    image: playwright-tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./playwright-report/e2e:/app/playwright-report/e2e
    command: npm run run-e2e-test
