name: Deploy Storybook and Playwright Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium with Dependencies
        run: npx playwright install chromium --with-deps

      - name: Run Playwright Component Tests
        run: npm run run-ct-test
        continue-on-error: true

      - name: Run Playwright E2E Tests
        run: npm run run-e2e-test
        continue-on-error: true

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            playwright-report/component
            playwright-report/e2e
            storybook-static
          destination_dir: /
          keep_files: true

      - name: Show Deployed URLs
        if: always()
        run: |
          echo "::notice title=Storybook URL::https://aniketicloud.github.io/playwright-react-18-vite-ts/"
          echo "::notice title=Playwright Component Tests URL::https://aniketicloud.github.io/playwright-react-18-vite-ts/playwright-report/component/"
          echo "::notice title=Playwright E2E Tests URL::https://aniketicloud.github.io/playwright-react-18-vite-ts/playwright-report/e2e/"
