name: Playwright e2e Tests
run-name: '${{ github.actor }} is running Playwright e2e tests 🚀'

on:
  pull_request:
    branches:
      - main # Run only on pull requests to the 'main' branch
  workflow_dispatch: # Allow manual runs

jobs:
  playwright-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Component Tests
        run: npm run run-e2e-test
