name: Playwright Component Tests

on:
  push:
    branches:
      - '**' # Run on any branch push
  pull_request:
    branches:
      - main # Run on pull requests to the 'main' branch
  workflow_dispatch: # Allow manual runs

jobs:
  playwright-component-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Component Tests
        run: npm run run-ct-test

      - name: Upload Component Test Report
        uses: actions/upload-artifact@v3
        with:
          name: component-test-report
          path: playwright-report/component
          retention-days: 30

      - name: Generate Badge for Tests
        run: |
          if [[ $(find playwright-report/component -name "*.html" | wc -l) -gt 0 ]]; then
            echo "All tests passed" > status.txt
            echo "![Tests Status](https://img.shields.io/badge/tests-passing-brightgreen)" > badge.svg
          else
            echo "Some tests failed" > status.txt
            echo "![Tests Status](https://img.shields.io/badge/tests-failing-red)" > badge.svg

      - name: Upload Test Status Badge
        uses: actions/upload-artifact@v3
        with:
          name: test-status-badge
          path: badge.svg

      - name: Upload Test Status
        uses: actions/upload-artifact@v3
        with:
          name: test-status
          path: status.txt
